languages:
  - code: en
    label: English
    active: true
  - code: gd
    label: Gàidhlig
    active: true
themes:
  - name: storlann 
rest:
  ssl: true
  host: api7.dspace.org
  port: 443
  nameSpace: /server
